VEN-1268 | Add berth information to order details
City-of-Helsinki/berth-reservations pull request #523
Opened 2021-04-09 07:07 UTC by klemmari1

## Description :sparkles:

Add berth information to OrderDetailsType. The field includes
a stringified version of the berth, for example:

Puotila (A) 1 `({harbor name} ({pier identifier}) {berth number})`

## Issues :bug:
### Closes :no_good_woman:
**[VEN-1268](https://helsinkisolutionoffice.atlassian.net/browse/VEN-1268): Add berth information to order details** 

### Related :handshake:

## Testing :alembic:
### Automated tests :gear:️

```
pytest payments/tests/test_payments_queries.py::test_get_order_status
```

### Manual testing :construction_worker_man:

## Screenshots :camera_flash:

## Additional notes :spiral_notepad:

2021-04-09 08:19 UTC, a-rmz requested changes
Sorry to change this so late on, but I just noticed the design was a bit different than I had originally thought.

Since the frontend needs to display the information on separate lines, we have to return them as separate fields:
<img width="326" alt="image" src="https://user-images.githubusercontent.com/15201480/114150964-4b3c1300-9925-11eb-968b-5bb2d0a89f5f.png">

So instead of `berth_information`, can you replace it for three fields `berth/pier/harbor`?
 
I updated the ticket with that description as well.

2021-04-09 08:25 UTC, klemmari1 commented
> Sorry to change this so late on, but I just noticed the design was a bit different than I had originally thought.
> 
> Since the frontend needs to display the information on separate lines, we have to return them as separate fields:
> <img alt="image" width="326" src="https://user-images.githubusercontent.com/15201480/114150964-4b3c1300-9925-11eb-968b-5bb2d0a89f5f.png">
> 
> So instead of `berth_information`, can you replace it for three fields `berth/pier/harbor`?
> 
> I updated the ticket with that description as well.

Alrighty, no problem. Not a big change.

2021-04-13 06:13 UTC, haavikko approved these changes
Looks good!

2021-04-13 07:02 UTC, a-rmz commented on payments/schema/types.py
> +    berth = graphene.String()
Can you mark this as required as well? 😇

2021-04-13 07:15 UTC, a-rmz approved these changes
![](https://media.giphy.com/media/QsJc1iCW3KfLG5Ol7o/giphy.gif)

2021-04-13 07:16 UTC, merged